### ISSUE TITLE
download deb is broken link

### ISSUE THREAD

**Issue by jswhisperer** [wordmark/wordmark#110]
https://github.com/wordmark/wordmark/releases/download/v3.0.1-beta.20/wordmark_3.0.1-beta.20_amd64.deb

**Comment by Torsten-K** [comment]
Yes, it’s broken since a long time, and there does not seem to exist a .deb file for version 3.0.2, nor an AppImage or whatever. Has the development for GNU/Linux been stopped?

**Comment by wordmark** [comment]
Hello, apologize! I haven't have much time recently but will fix this soon.

**Comment by Torsten-K** [comment]
Ah, okay, no worries, thanks for the information.

**Comment by djdembeck** [comment]
I'm seeing this issue too, any updates?

**Comment by jeremias-jordan** [comment]
I would be interested in updates as well

**Comment by ram-a-dhan** [comment]
Still no update yet?

**Comment by johnblommers** [comment]
So I've been using 3.0.1-beta 19 with good results on Pop!_OS (Ubuntu 20.10 and GNOME).

Beta 20 is still missing in action. This is unfortunate. Let me express hope that the developer is able to upload the latest goodness that is WordMark. 

It's April 2021 and Ubuntu 21.04 is about to escape. That means GNOME 40 and Wayland will be the default. Will WordMark run all right on it?

WordMark is just too good to leave it in an uncertain state.

**Comment by wordmark** [comment]
Hi all,

Sorry for not fixing this for long time! I have been working on building the new mac version with native language to avoid using Electron because of its large file size / high use of resources. I am not a Linux user myself, but I would definitely want to keep developing this. I am looking in the market to see if there are any Electron alternatives (maybe Flutter). Let me see if I can quickly add a linux build using the current codebase.

**Comment by johnblommers** [comment]
Thank you @wordmark. 

I'm using Wordmark on a daily basis on my Linux box. It's a very nice-to-use single-pane live update WYSIWYG Markdown editor. You should be very proud of it. Being able to run the very latest version on Linux would totally be appreciated. Thanks for your quick reply.

**Comment by johnblommers** [comment]
I've been following the efforts of @wordmark  on the macOS side and the product is going strong there. Well done!

Please consider revisiting the Linux version as soon as you are able. We are waiting for an update eagerly :-)

**Comment by wordmark** [comment]
Apologize for not updating the linux & windows version yet. Things are really going crazy recently, my old ubuntu machine that I used for testing is becoming unreasonbly slow. I was trying to install a linux system on the PC but the machine is currently occupied due to WFH. Please allow some time so that I can get a solution for this.

**Comment by johnblommers** [comment]
Of course, good @wordmark. Testing new releases of WYSIWYG Markdown software floats my boat. I'll stand by the dock for now. Best wishes.

**Comment by johnblommers** [comment]
Just to be clear, version 3.0.1-beta.19 is the last properly working Linux binary distributed by this project. Launching it will report that version 3.1.0 is ready, but that download remains defective.

**Comment by johnblommers** [comment]
Any progress on this front?

**Comment by wordmark** [comment]
Thank you for following up on this. I have been focusing on improving the core engine (the editor) for these months. Will put this on top of my list.

**Comment by wordmark** [comment]
The download link for 3.1.1 should be fixed now. 

https://github.com/wordmark/wordmark/releases/tag/3.1.1

**Comment by Torsten-K** [comment]
3.1.1 works perfectly on my Xubuntu 20.04. Thank you so much for publishing!

**Comment by johnblommers** [comment]
3.1.1 installs and runs just fine on PopOS 22.04 (fork of Ubuntu 22.04 GNOME 42).

I might add that it looks as polished as I remember it.

Many thanks
